M48
; DRILL file KiCad 10.0.1 date 2026-06-14T11:07:26
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-14T11:07:26+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X138.82Y-90.09
X144.6Y-90.09
T2
X111.82Y-65.73
X111.82Y-88.73
X169.82Y-65.73
X169.82Y-88.73
T3
X125.57Y-61.98
X125.57Y-92.48
X156.07Y-61.98
X156.07Y-92.48
M30
